#!/bin/sh
set -x
HS=40
# this depth and model gives a spectra hole at 33-40 sec
STK=0
RAKE=0
DIP=90
AZ=45
NMODE=10
######
# changing the RAKE to 45 removes some of the spectral hole
# =0 Strike slip if dip is 90
# =90 dip slip is dip is 45 -- good hole
######
cat > dfile << EOF
500.0 1.000 2048 -1.0 8.0
1000.0 1.000 2048 -1.0 8.0
2000.0 1.000 2048 -1.0 8.0
3000.0 1.000 2048 -1.0 8.0
4000.0 1.000 2048 -1.0 8.0
8000.0 1.000 2048 -1.0 8.0
EOF
cat > model.d << EOF
MODEL
TEST MODEL
ISOTROPIC
KGS
FLAT EARTH
1-D
CONSTANT VELOCITY
LINE08
LINE09
LINE10
LINE11
HR VP VS RHO QP QS ETAP ETAS FREFP FREFS
40. 6.0 3.5 2.8 0.0 0.0 0.0 0.0 1.0 1.0
00. 8.0 4.7 3.3 0.0 0.0 0.0 0.0 1.0 1.0
EOF
#####
# Chapter 3
#####
sprep96 -M model.d -NMOD ${NMODE} -HS ${HS} -HR 0 -d dfile -L -R
sdisp96
sregn96
slegn96
sdpegn96 -R -U -PER -TXT -XLOG -YMIN 2.5 -YMAX 5
sdpegn96 -L -U -PER -TXT -XLOG -YMIN 2.5 -YMAX 5
sdpegn96 -R -C -PER -ASC -XMIN 20.0 -XMAX 150.0 -YMIN 3.0 -YMAX 5.0
sdpegn96 -L -C -PER -ASC -XMIN 20.0 -XMAX 150.0 -YMIN 3.0 -YMAX 5.0
#plotxvig < SREGNU.PLT
#plotxvig < SLEGNU.PLT
spulse96 -d dfile -D -p -EQ -2 > file96
fmech96 -A ${AZ} -ROT -D ${DIP} -R ${RAKE} -S ${STK} -M0 1.0E+20 < file96 > 3.96
f96tosac -B 3.96
cp B00101Z00.sac Z1.sac
cp B00201Z00.sac Z2.sac
cp B00301Z00.sac Z3.sac
cp B00401Z00.sac Z4.sac
cp B00501Z00.sac Z5.sac
cp B00601Z00.sac Z6.sac
rm -f B*.sac

for MODE in 0 1 2 3 4 5 6 7
do
spulse96 -d dfile -D -p -EQ -2 -M ${MODE} | \
fmech96 -A ${AZ} -ROT -D ${DIP} -R ${RAKE} \
-S ${STK} -M0 1.0E+20 > 3.96.${MODE}
f96tosac -B 3.96.${MODE}
cp B00101Z00.sac Z1.${MODE}.sac
cp B00201Z00.sac Z2.${MODE}.sac
cp B00301Z00.sac Z3.${MODE}.sac
cp B00401Z00.sac Z4.${MODE}.sac
cp B00501Z00.sac Z5.${MODE}.sac
cp B00601Z00.sac Z6.${MODE}.sac
done
rm -f B*sac


